export const LS_TOKEN = 'LS_TOKEN';
export const LS_ACCOUNT = 'LS_ACCOUNT';
export const LS_MODULES = 'LS_MODULES';

export const DIALOG_TYPE_ALERT = 'DIALOG_TYPE_ALERT';
export const DIALOG_TYPE_CONFIRMATION = 'DIALOG_TYPE_CONFIRMATION';

export const SESSION_EXPIRED_ERROR_MESSAGE = 'Invalid Session or Session expired.';

export const TESTD_AC_ID = 'TESTD_AC_ID';
export const TESTD_AC_LOCATION_INFO = 'TESTD_AC_LOCATION_INFO';
export const TESTD_AC_USER_ID = 'TESTD_AC_USER_ID';
export const TESTD_AC_USER_DATA = 'TESTD_AC_USER_DATA';
export const TESTD_AC_QUESTIONS_DATA = 'TESTD_AC_QUESTIONS_DATA';
export const TESTD_AC_HAVE_INSURANCE = 'TESTD_AC_HAVE_INSURANCE';
export const TESTD_AC_PATIENT_DATA = 'TESTD_AC_PATIENT_DATA';