export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const API_ERROR = 'API_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const SHOW_DIALOG = 'SHOW_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const SHOW_ALERT_DIALOG = 'SHOW_ALERT_DIALOG';
export const SHOW_CONFIRMATION_DIALOG = 'SHOW_CONFIRMATION_DIALOG';

export const FETCH_DASHBOARD_COUNTS = 'FETCH_DASHBOARD_COUNTS';
export const FETCH_DASHBOARD_AGE_RISK = 'FETCH_DASHBOARD_AGE_RISK';
export const FETCH_DASHBOARD_LOCATION_RISK = 'FETCH_DASHBOARD_LOCATION_RISK';

export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';

export const FETCH_REPORTING_COMPLIANCE_COUNTS = 'FETCH_REPORTING_COMPLIANCE_COUNTS';
export const FETCH_REPORTING_COMPLIANCE_LINEAR = 'FETCH_REPORTING_COMPLIANCE_LINEAR';
export const FETCH_REPORTING_COMPLIANCE_TESTS = 'FETCH_REPORTING_COMPLIANCE_TESTS';
export const FETCH_REPORTING_COMPLIANCE_LIST = 'FETCH_REPORTING_COMPLIANCE_LIST';

export const FETCH_REPORTING_USER_LINEAR = 'FETCH_REPORTING_USER_LINEAR';
export const FETCH_REPORTING_USER_LIST = 'FETCH_REPORTING_USER_LIST';

export const FETCH_REPORTING_SITE_COUNTS = 'FETCH_REPORTING_SITE_COUNTS';
export const FETCH_REPORTING_SITE_LINEAR = 'FETCH_REPORTING_SITE_LINEAR';
export const FETCH_REPORTING_SITE_TESTS = 'FETCH_REPORTING_SITE_TESTS';
export const FETCH_REPORTING_SITE_LIST = 'FETCH_REPORTING_SITE_LIST';

export const FETCH_REPORTING_LAB_COUNTS = 'FETCH_REPORTING_LAB_COUNTS';
export const FETCH_REPORTING_LAB_LINEAR = 'FETCH_REPORTING_LAB_LINEAR';
export const FETCH_REPORTING_LAB_TESTS = 'FETCH_REPORTING_LAB_TESTS';
export const FETCH_REPORTING_LAB_LIST = 'FETCH_REPORTING_LAB_LIST';

// Clear
export const CLEAR_REPORTING_COMPLIANCE = 'CLEAR_REPORTING_COMPLIANCE';
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS';
export const CLEAR_DEPARTMENTS = 'CLEAR_DEPARTMENTS';
export const CLEAR_ALL_DATA = 'CLEAR_ALL_DATA';