export default {
  type: '',
  first_name_hide: false,
  first_name_required: true,
  last_name_hide: false,
  last_name_required: true,
  email_hide: false,
  email_required: true,
  phone_hide: false,
  phone_required: true,
  address_hide: false,
  address_required: true,
  // intake settings
  web_intake_type: '',
  testing_protocol: '',
  vaccine_protocol: '',
  health_screening_hide: false,
  health_screening_required: true,
  health_condition_hide: false,
  health_condition_required: true,
  last_14days_contact_hide: false,
  last_14days_contact_required: true,
  contact_information_hide: false,
  contact_information_required: true,
  home_address_hide: false,
  home_address_required: true,
  demographics_ssn_hide: false,
  demographics_ssn_required: true,
  insurance_information_hide: false,
  insurance_information_required: true,
  personal_identity_hide: false,
  personal_identity_required: true,
};
