export { default as Question1 }  from './Question1';
export { default as Question2 }  from './Question2';
export { default as Question3 }  from './Question3';
export { default as Question4 }  from './Question4';
export { default as Question5 }  from './Question5';
export { default as Question6 }  from './Question6';
export { default as Question7 }  from './Question7';
export { default as Question8 }  from './Question8';
export { default as Question9 }  from './Question9';
export { default as Question10 }  from './Question10';
// export { default as Question11 }  from './Question11';
// export { default as Question12 }  from './Question12';
// export { default as Question13 }  from './Question13';
// export { default as Question14 }  from './Question14';
